---
- hosts: db
  vars:
  tasks:

      include_vars: vault.yml
    
    - name: Copy mariadb to yum 
      become: true
      copy: src=db/MariaDB.repo dest=/etc/yum.repos.d/MariaDB.repo mode=0644
       #copy task copies what is in the db folder into etc folder

    - name: Dl MariaDB server
      become: yes
      yum: name=MariaDB-client update_cache=yes state=present
     

    - name: Unpack db.tgz to localhost
      become: true
      unarchive: src=db/db.tgz dest=~/ mode=0777
      #unpacks and open the 

    - name: Make DB
      become: yes 
      command: ./make_databases.sh {{ db_password }} tf-20161215040828888518624i4p.calt7kdaagno.us-west-2.rds.amazonaws.com:3306 chdir=~/db
      ignore_errors: True
      #cd backs into old dir; ignore_errors ignores any errors that do occur
      # change endpoint for db each it is destroyed
